import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const Icon = ({children}) => <span className="icon">{children}</span>;
const nav = [['⌂','Overview'],['◫','Practice'],['◉','Analytics'],['✦','AI Doubts'],['♧','Community'],['♜','Leaderboard']];
const questions = [
  {subject:'Biology', tag:'Cell: The Unit of Life', q:'Which cell organelle is known as the powerhouse of the cell?', options:['Golgi apparatus','Mitochondria','Ribosome','Lysosome'], answer:1},
  {subject:'Chemistry', tag:'Chemical Bonding', q:'The hybridisation of carbon in methane is:', options:['sp','sp²','sp³','dsp²'], answer:2},
  {subject:'Physics', tag:'Laws of Motion', q:'The SI unit of impulse is:', options:['Newton','Newton second','Joule','Watt'], answer:1},
];

function App(){
 const [page,setPage]=useState('Overview'); const [quizOpen,setQuizOpen]=useState(false); const [idx,setIdx]=useState(0); const [choice,setChoice]=useState(null); const [score,setScore]=useState(0); const [message,setMessage]=useState('');
 const startQuiz=()=>{setQuizOpen(true);setIdx(0);setChoice(null);setScore(0)};
 const next=()=>{if(choice===questions[idx].answer)setScore(s=>s+1); if(idx===questions.length-1){setQuizOpen(false);setPage('Analytics');return} setIdx(i=>i+1);setChoice(null)};
 return <div className="app">
  <aside className="sidebar"><div className="brand"><div className="mark">N</div><div>nex<span>NEET</span><small>PREP COMMUNITY</small></div></div>
   <div className="nav-label">LEARNING SPACE</div>{nav.map(([i,n])=><button key={n} className={'nav '+(page===n?'selected':'')} onClick={()=>setPage(n)}><Icon>{i}</Icon>{n}{n==='AI Doubts'&&<b>5</b>}</button>)}
   <div className="sidebar-bottom"><div className="upgrade"><span>✦</span><strong>NEET 2026</strong><small>281 days to go</small></div><div className="student"><div className="avatar">AS</div><div><strong>Arjun Sharma</strong><small>Level 12 · Rising Star</small></div><span>⌄</span></div></div>
  </aside>
  <main><header><div className="mobile-brand">nex<span>NEET</span></div><div className="crumb">STUDENT SPACE <i>/</i> <strong>{page}</strong></div><div className="top-actions"><button className="circle">⌕</button><button className="circle notification">♧</button><button className="profile">AS</button></div></header>
   {page==='Overview' && <Overview startQuiz={startQuiz} setPage={setPage}/>} {page==='Practice' && <Practice startQuiz={startQuiz}/>} {page==='Analytics' && <Analytics/>} {page==='AI Doubts' && <Doubts message={message} setMessage={setMessage}/>} {page==='Community' && <Community/>} {page==='Leaderboard' && <Leaderboard/>}
  </main>{quizOpen&&<Quiz q={questions[idx]} idx={idx} choice={choice} setChoice={setChoice} next={next} score={score}/>} 
 </div>
}
function Overview({startQuiz,setPage}){return <div className="content"><section className="hero"><div><p className="eyebrow">TUESDAY, SEPTEMBER 2</p><h1>Good morning, Arjun <span>✦</span></h1><p className="sub">Small, focused practice today brings you closer to your dream college.</p><div className="hero-actions"><button className="primary" onClick={startQuiz}>Start today's quiz <span>→</span></button><button className="text-btn" onClick={()=>setPage('Practice')}>View study plan</button></div></div><div className="hero-visual"><div className="orbit o1"></div><div className="orbit o2"></div><div className="target">◉<small>DAY<br/>43</small></div><div className="fire">🔥</div></div></section>
 <section className="metrics"><Metric emoji="🔥" value="12" label="DAY STREAK" note="Best: 18 days"/><Metric emoji="⌁" value="72%" label="PREP SCORE" note="↑ 6% this month"/><Metric emoji="◈" value="2,840" label="XP EARNED" note="160 XP to Level 13"/><Metric emoji="◷" value="4.6h" label="STUDY THIS WEEK" note="Goal: 10 hours"/></section>
 <div className="grid-main"><section className="card focus"><div className="card-head"><div><p className="eyebrow">YOUR ADAPTIVE PATH</p><h2>Continue your focus</h2></div><button className="more">•••</button></div><div className="focus-inner"><div className="subject-pill bio">BIOLOGY <span>•</span> FOUNDATIONS</div><h3>Plant Kingdom</h3><p>Strengthen your basics before moving ahead.</p><div className="progress"><span style={{width:'68%'}}></span></div><div className="progress-info"><span>68% mastery</span><span>17 / 25 concepts</span></div><button className="outline" onClick={startQuiz}>Practice this topic <span>→</span></button></div></section>
 <section className="card weak"><div className="card-head"><div><p className="eyebrow">SMART INSIGHT</p><h2>Areas to strengthen</h2></div><button className="more">•••</button></div><Weak topic="Human Physiology" percent="54" color="#f06b61"/><Weak topic="Chemical Bonding" percent="61" color="#f4b64e"/><Weak topic="Rotational Motion" percent="64" color="#7466d9"/><button className="link-btn" onClick={()=>setPage('Analytics')}>View full analysis →</button></section></div>
 <div className="grid-main lower"><section className="card quiz-card"><div className="quiz-icon">✦</div><div><p className="eyebrow">DAILY MIX · 15 QUESTIONS · 12 MIN</p><h2>Today's Quick Quiz</h2><p>Keep your streak alive and earn up to <strong>120 XP</strong>.</p></div><button className="primary compact" onClick={startQuiz}>Begin quiz →</button></section><section className="card upcoming"><div className="card-head"><h2>Coming up</h2><button className="link-btn">See all</button></div><div className="event"><span className="date"><b>06</b>SEP</span><div><strong>Weekly Full Syllabus Test</strong><small>Sunday · 10:00 AM · 180 questions</small></div><span>›</span></div></section></div></div>}
const Metric=({emoji,value,label,note})=><div className="metric"><span className="metric-emoji">{emoji}</span><div><strong>{value}</strong><p>{label}</p><small>{note}</small></div></div>;
const Weak=({topic,percent,color})=><div className="weak-row"><div className="weak-name"><span style={{background:color}}></span>{topic}</div><div className="bar"><i style={{width:percent+'%',background:color}}></i></div><b>{percent}%</b></div>;
function Practice({startQuiz}){return <div className="content simple-page"><p className="eyebrow">PERSONALISED PRACTICE</p><h1>What would you like to master?</h1><p className="sub">Your next questions are selected from the topics that will make the biggest difference.</p><div className="practice-grid">{[['🧬','Biology','42 chapters','Your strongest subject'],['⚗','Chemistry','31 chapters','2 topics need attention'],['◉','Physics','29 chapters','Continue building momentum']].map((x,i)=><div className="subject-card" key={x[1]}><span>{x[0]}</span><p>{x[1]}</p><h2>{x[2]}</h2><small>{x[3]}</small><button className="outline" onClick={startQuiz}>Practice now →</button></div>)}</div><section className="card mock"><div><p className="eyebrow">EXAM SIMULATOR</p><h2>NEET-style mock tests</h2><p>Build focus and confidence in the real exam format.</p></div><button className="primary" onClick={startQuiz}>Take a mock →</button></section></div>}
function Analytics(){return <div className="content simple-page"><p className="eyebrow">YOUR PROGRESS</p><h1>Preparation analytics</h1><div className="analytics-top"><section className="card score-ring"><div className="ring"><strong>72<small>%</small></strong></div><div><h2>Preparation score</h2><p>You're progressing faster than 68% of learners this month.</p><span className="up">↑ 6 points this month</span></div></section><section className="card chart"><div className="card-head"><h2>Weekly accuracy</h2><span className="up">↑ 9.4%</span></div><div className="bars">{[38,55,44,63,58,76,72].map((h,i)=><div key={i}><i style={{height:h+'%'}}></i><small>{['M','T','W','T','F','S','S'][i]}</small></div>)}</div></section></div><section className="card subject-table"><h2>Subject performance</h2>{[['Biology','78','#36a87e'],['Chemistry','68','#f2af4b'],['Physics','62','#7769d8']].map(([s,p,c])=><div className="subject-line" key={s}><strong>{s}</strong><div className="bar"><i style={{width:p+'%',background:c}}></i></div><b>{p}%</b><span>View analysis →</span></div>)}</section></div>}
function Doubts({message,setMessage}){const [chat,setChat]=useState([{from:'ai',text:'Hi Arjun! I’m your NEET study companion. What concept can I help you understand today?'}]);const send=()=>{if(!message.trim())return;setChat(c=>[...c,{from:'me',text:message},{from:'ai',text:'Great question. Let’s break this down step by step. I’ll explain the core concept, then give you a quick way to remember it for NEET.'}]);setMessage('')};return <div className="content doubts"><div className="doubt-head"><div><p className="eyebrow">AI STUDY COMPANION</p><h1>Clear your doubts, instantly.</h1><p className="sub">NEET-focused answers that help concepts stick.</p></div><div className="sessions"><b>✦ 5</b><small>free sessions left today</small></div></div><div className="chat card">{chat.map((x,i)=><div className={'bubble '+x.from} key={i}>{x.from==='ai'&&<span>✦</span>}<p>{x.text}</p></div>)}<div className="suggestions"><button onClick={()=>setMessage('Explain the difference between mitosis and meiosis')}>Explain mitosis vs meiosis</button><button onClick={()=>setMessage('Help me understand hybridisation')}>Understand hybridisation</button></div><div className="ask"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask anything about NEET..."/><button onClick={send}>↑</button></div></div></div>}
function Community(){return <div className="content simple-page"><p className="eyebrow">LEARN TOGETHER</p><h1>The community is studying</h1><div className="community-grid"><section>{['How did you revise human physiology?','Best mnemonics for periodic table','Today’s biology quiz discussion'].map((x,i)=><article className="post card" key={x}><div className="avatar">{['KV','PS','MR'][i]}</div><div><small>{['Kavya Verma','Priyansh Singh','Meera R'][i]} · {i+1}h ago</small><h2>{x}</h2><p>Join the discussion with fellow NEET aspirants and share your approach.</p><span>♡ {12+i*7} &nbsp; ◯ {4+i}</span></div></article>)}</section><aside className="card groups"><h2>Popular study groups</h2><p>🧬 Biology 2026 <b>2.1k members</b></p><p>⚗ Chemistry Daily <b>1.8k members</b></p><p>◉ Physics Problem Lab <b>980 members</b></p><button className="primary">Explore groups</button></aside></div></div>}
function Leaderboard(){let names=['Aarav Mehta','Sneha Patel','Arjun Sharma','Riya Nair','Kabir Shah'];return <div className="content simple-page"><p className="eyebrow">THIS WEEK</p><h1>Leaderboard</h1><p className="sub">Celebrate consistency. Your progress is the real win.</p><section className="podium"><div>2<small>Sneha</small></div><div>1<small>Aarav</small></div><div>3<small>You</small></div></section><section className="card rankings">{names.map((n,i)=><div key={n} className={n==='Arjun Sharma'?'mine':''}><b>#{i+1}</b><span className="avatar">{n.split(' ').map(a=>a[0]).join('')}</span><strong>{n}</strong><span>{[3250,3010,2840,2690,2520][i]} XP</span></div>)}</section></div>}
function Quiz({q,idx,choice,setChoice,next,score}){return <div className="modal-back"><section className="quiz-modal"><div className="quiz-top"><span>DAILY QUIZ</span><b>{idx+1} / 3</b><button onClick={()=>location.reload()}>×</button></div><div className="quiz-progress"><i style={{width:(idx+1)/3*100+'%'}}></i></div><p className="subject-tag">{q.subject.toUpperCase()} · {q.tag}</p><h2>{q.q}</h2><div className="options">{q.options.map((o,i)=><button key={o} className={choice===i?'picked':''} onClick={()=>setChoice(i)}><b>{'ABCD'[i]}</b>{o}</button>)}</div><div className="quiz-footer"><span>{score} correct so far</span><button className="primary" disabled={choice===null} onClick={next}>{idx===2?'Finish quiz':'Next question'} →</button></div></section></div>}
createRoot(document.getElementById('root')).render(<App/>);
